swagger: "2.0"
info:
  title: "Read All Categories"
  description: "Retrieves all categories"
  version: "1.0.0"
produces:
  - "application/json"
responses:
  200:
    description: "Success"
    schema:
      type: "object"
      properties:
        Code:
          type: "integer"
          format: "int32"
        Code Type:
          type: "string"
        Data:
          type: "array"
          items:
            type: "object"
            properties:
              name:
                type: "string"
                description: "The name of the category"
              description:
                type: "string"
                description: "The short description of the category"
